version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command:  bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - C:\Users\lujeb\Documents\github_projects\bachelor_project\reciprocal_blast_pipeline\data:/blast/media
      - C:\Users\lujeb\Documents\github_projects\bachelor_project\reciprocal_blast_pipeline\tmp:/blast/tmp
      - C:\Users\lujeb\Documents\blast\db:/blast/nr_database
    ports:
      - "8000:8000"
      - "5000:5000"
    depends_on:
      - db

