version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command:  bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./data:/blast/reciprocal_blast/media
      - ./tmp:/blast/reciprocal_blast/tmp
      - ./reciprocal_blast:/blast/reciprocal_blast
    ports:
      - "8080:8080"
      - "5000:5000"
    depends_on:
      - db

