configfile: "C:/Users/lujeb/Documents/github_projects/reciprocal_blast_pipeline/data/snakemake_config"

rule all:
	input:
		"reciprocal_best_hits_protein_ids.txt"

rule make_forward_database:
	input: config['fw_db']
	output: config['fw_db']+'.pdb'
	params: blast_out=config['fw_db']
	shell: "makeblastdb -in {input} -dbtype prot -out {params.blast_out}"

rule forward_blast:
	input: query=config['fw_query'], db=config['fw_db']+".pdb"
	output: "forward_blast_output.csv"
	params: blast_in=config['fw_db'], word_size=config['fw_word_size'], e_value=config['fw_evalue'], num_alignments=config['fw_num_alignments']
	shell: "blastp -db {params.blast_in} -query {input.query}  -outfmt 10 -word_size {params.word_size} -evalue {params.e_value} -num_alignments {params.num_alignments} -out {output} "

rule get_backward_sequences:
	input: blast_results="forward_blast_output.csv", fw_genome=config['fw_db']
	output: config['bw_query']
	script: 
		"process_fw_blast_results.py"

rule make_backward_database:
	input: config['bw_db']
	output: config['bw_db']+'.pdb'
	params: blast_out=config['bw_db']
	shell: "makeblastdb -in {input} -dbtype prot -out {params.blast_out}"

rule backward_blast:
	input: query=config['bw_query'], db=config['bw_db']+".pdb"
	output: "backward_blast_output.csv"
	params: blast_in=config['bw_db'], word_size=config['bw_word_size'], e_value=config['bw_evalue'], num_alignments=config['bw_num_alignments']
	shell: "blastp -db {params.blast_in} -query {input.query}  -outfmt 10 -word_size {params.word_size} -evalue {params.e_value} -num_alignments {params.num_alignments} -out {output} "

rule get_reciprocal_best_hits_proteins_ids:
	input: bw_result="backward_blast_output.csv", fw_result="forward_blast_output.csv"
	output: "reciprocal_best_hits_protein_ids.txt"
	script: 
		"extract_valid_accession_ids_from_blast_results.py"

