# Generated by Django 2.2.5 on 2021-01-29 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, unique=True)),
                ('search_strategy', models.CharField(choices=[('blastp', 'blastp'), ('blastn', 'blastn')], default='blastp', max_length=20)),
                ('pipeline_executed', models.BooleanField(default=False)),
                ('using_nr_database', models.BooleanField(default=False)),
                ('project_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxNodesForForwardDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomic_node', models.IntegerField()),
                ('organism_name', models.CharField(max_length=200)),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastProject')),
            ],
        ),
        migrations.CreateModel(
            name='TaxNodesForBackwardDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomic_node', models.IntegerField()),
                ('organism_name', models.CharField(max_length=200)),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastProject')),
            ],
        ),
        migrations.CreateModel(
            name='QuerySequences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_file_name', models.CharField(max_length=200)),
                ('path_to_query_file', models.CharField(max_length=300)),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastProject')),
            ],
        ),
        migrations.CreateModel(
            name='Genomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciprocal_type', models.CharField(choices=[('forward', 'forward'), ('backward', 'backward')], max_length=200)),
                ('genome_name', models.CharField(max_length=200)),
                ('path_to_file', models.CharField(max_length=300)),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastProject')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardBlastSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_value', models.DecimalField(decimal_places=15, default=0.0001, max_digits=30)),
                ('word_size', models.IntegerField(default=3)),
                ('num_alignments', models.IntegerField(default=10000)),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastProject')),
            ],
        ),
        migrations.CreateModel(
            name='BackwardBlastSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_value', models.DecimalField(decimal_places=15, default=0.0001, max_digits=30)),
                ('word_size', models.IntegerField(default=3)),
                ('num_alignments', models.IntegerField(default=1)),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastProject')),
            ],
        ),
    ]
