# Generated by Django 3.1.4 on 2021-01-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_project', '0002_auto_20210130_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomes',
            name='reciprocal_type',
            field=models.CharField(blank=True, choices=[('forward', 'forward'), ('backward', 'backward')], max_length=200, null=True),
        ),
    ]
