# Generated by Django 3.1.4 on 2021-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_project', '0003_auto_20210130_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='backwardblastsettings',
            name='max_hsps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backwardblastsettings',
            name='max_target_seqs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backwardblastsettings',
            name='num_descriptions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backwardblastsettings',
            name='num_threads',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='forwardblastsettings',
            name='max_hsps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forwardblastsettings',
            name='max_target_seqs',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='forwardblastsettings',
            name='num_descriptions',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='forwardblastsettings',
            name='num_threads',
            field=models.IntegerField(default=1),
        ),
    ]
