# Generated by Django 3.0.3 on 2021-02-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blast_project', '0004_auto_20210201_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backwardblastsettings',
            name='max_target_seqs',
        ),
        migrations.RemoveField(
            model_name='forwardblastsettings',
            name='max_hsps',
        ),
        migrations.RemoveField(
            model_name='forwardblastsettings',
            name='max_target_seqs',
        ),
    ]
